config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: :about
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
        profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    # sign in後にuser/showへ遷移するよう変更
    user_path(resource)
   end



  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
   end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @new = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new = Book.new
    # 投稿内容に紐づいたuser情報を持ってくる
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to '/books'
    end
  end


  def create
    # データを受け取り新規登録するためのインスタンス作成
    @new = Book.new(book_params)
    # 投稿したデータにログイン中のユーザーのIDを持たせる
    @new.user_id = current_user.id
    # データをデータベースに保存するためのsaveメソッド実行
    if @new.save
    # booksのshow画面へリダイレクト
       redirect_to book_path(@new.id), notice: 'Book was successfully created.'
    else
       @books = Book.all
       @user = current_user
       render :index
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
     # データ（レコード）を1件取得
    book = Book.find(params[:id])
    # データ（レコード）を削除
    book.destroy
    # 投稿一覧画面へリダイレクト
    flash[:notice] = 'Book was successfully destroyed.'
    redirect_to books_path
  end


  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @user = current_user
    @new = Book.new
  end

  def show
    @user = User.find(params[:id])
    # 特定のユーザ(@user)に紐づいた投稿をすべて取得
    @books = @user.books
    @new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User was successfully updated.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
<!--共通テンプレート-->
    <div class="col-md-3">
      
      <h2>User info</h2>
      <!--プロフィール画像-->
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
           <!--userのプロフィール編集画面へのリンクボタン-->
      <div class="row">
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <!--投稿フォーム-->
      <h2 class="mt-3">New book</h2>
      <%= form_with model: new do |f| %>

      <div class="form-group">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <label for="book_body">Opinion</label><br>
        <%= f.text_area :body %>
      </div>

      <div clas="form-group">
        <%= f.submit 'Create Book' %>
      </div>
      <% end %>
    </div>
    <!--共通テンプレート-->

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <div class="error_explanation">
       <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
    　     <% @book.errors.full_messages.each do |message| %>
      　　   　<li><%= message %></li>
    　　    <% end %>
  　　　　</ul>
　　　<% end %>
      </div>

      <h1>Editing Book</h1>
      <%= form_with model: @book, url: book_path(@book.id) ,method: :patch do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label><br>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label><br>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book' %>
        </div>
      <% end %>
      <!--投稿の詳細画面へ-->
      <%= link_to 'Show', book_path(@book.id), method: :get %> | <%= link_to 'Back', '/books' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <div class="error_explanation">
    <% if @new.errors.any? %>
  　　<%= @new.errors.count %>errors prohibited this obj from being saved:
  　　<ul>
    　　<% @new.errors.full_messages.each do |message| %>
      　　<li><%= message %></li>
    　　<% end %>
  　　</ul>
　　<% end %>
  </div>

  <div class="row">

    <!--共通テンプレート-->
    <%= render 'books/user_info', user: @user, new: @new %>

    <!--右：投稿一覧　投稿したユーザーのprofile_image-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <!--投稿に紐づくユーザーの画像-->
            <td>

            <%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user) %>
            </td>
            <!--ユーザーが投稿したtitle-->
            <td>
              <%= link_to book.title , book_path(book.id) %>
            </td>
            <!--ユーザーが投稿したbody-->
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--フラッシュメッセージ-->
<div class="flash-notifications">
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>

<div class="container">
  <div class="row">
   <!--部分テンプレート-->
   <%= render 'books/user_info', user: @user, new: @new %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <!--投稿したユーザの画像と名前-->
            <td>
              <%= link_to image_tag(@book.user.get_profile_image(100,100)), user_path(@book.user.id) %><br>
              <%= link_to @book.user.name, user_path(@book.user.id) %>
            </td>
            <td>
              <%= link_to  @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book.id),  class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "削除しますか？"} %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <P id="notice"></P>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        welcome to
        <i class="fas fa-book">
        </i>
        <strong>Bookers</strong>
        !
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <!--フラッシュメッセージ-->
  <div class="flash-notifications">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: key) %>
    <% end %>
  </div>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-g-8 col-xl-6">
                <h1>
                   welcome to
                   <i class="fas fa-book"></i>
                   <strong>Bookers</strong>
                   !!
                </h1>
                <p>
                    In
                    <i class="fas fa-book"></i>
                    <strong>Bookers</strong>
                    ,
                </p>
                <p>you can share and exchange yur opinions , inpressions , and emotions</p>
                <p>about various books!</p>
                <div class="btn-wrapper col-10 mx-auto">
                    <div class="row">
                        <%=link_to "Log in", '/users/sign_in', class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                    </div>
                    <div class="row">
                        <%=link_to "Sign up", '/users/sign_up', class: "btn btn-success btn-sm btn-block mb-3 sign_up" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to '/', class: "navbar-brand" do %>
             <span>Bookers</span>
          <% end %>
          <!--ハンバーガー-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!--headrの右側-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!--userの詳細画面-->
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  <span>Home</span>
                <% end %>
              </li>
              <!--userの一覧画面-->
              <li>
                 <%= link_to '/users', class: "nav-link text-light" do %>
                   <i class="fas fa-users"></i>
                  <span>Users</span>
                <% end %>
              </li>
              <!--bookの一覧画面-->
              <li>
                 <%= link_to '/books', class: "nav-link text-light" do %>
                   <i class="fas fa-book-open"></i>
                  <span>Books</span>
                <% end %>
              </li>
              <!--Log out-->
              <li>
                <%= link_to '/users/sign_out', class: "nav-link text-light", method: :delete do %>
                   <i class="fas fa-sign-out-alt"></i>
                  <span>Log out</span>
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to '/', class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  <span>Home</span>
                <% end %>
              </li>
              <!--homesのaboutページ-->
              <li>
                 <%= link_to '/home/about', class: "nav-link text-light" do %>
                   <i class="fas fa-link"></i>
                  <span>About</span>
                <% end %>
              </li>
              <li>
                <%= link_to '/users/sign_up', class: "nav-link text-light" do %>
                   <i class="fas fa-user-plus"></i>
                  <span>Sign up</span>
                <% end %>
              </li>
              <li>
                <%= link_to '/users/sign_in', class: "nav-link text-light" do %>
                   <i class="fas fa-sign-in-alt"></i>
                  <span>Log in</span>
                <% end %>
                </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <div class="error_explanation">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>errors prohibited this obj from being saved:
          <ul>
    　       <% @user.errors.full_messages.each do |message| %>
      　　     　<li><%= message %></li>
    　　      <% end %>
  　　　   　</ul>
　　　  <% end %>
      </div>

      <h2>User info</h2>
      <%= form_with model: @user, url: user_path(@user.id) ,method: :patch do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label><br>
          <%= f.text_field :name, autfocus: true %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label><br>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <!--部分テンプレート-->
      <%= render 'books/user_info', user: @user, new: @new %>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<!--フラッシュメッセージ-->
<div class="flash-notifications">
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>

<div class="container">
  <div class="row">
   <!--共通テンプレート-->
   <%= render 'books/user_info', user: @user, new: @new %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to image_tag(@user.get_profile_image(100,100)), user_path(@user) %>
            </td>
            <!--user_idに紐づいた投稿を持ってくる-->
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          <% end %>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>